import { AppShell } from "@/components/app/shell";
import { deleteServiceCategoryAction, saveServiceCategoryAction } from "@/lib/actions/marketplace";
import { createServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const input = "rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[#F2811D]";
export default async function ServiceCategoriesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const params = await searchParams;
  const supabase = await createServerClient();
  const { data } = await supabase.from("service_categories").select("*").order("parent_id", { nullsFirst: true }).order("display_order").order("name");
  const roots = data?.filter((item) => !item.parent_id) ?? [];
  return <AppShell eyebrow="Administrador" title="Categorias de serviços">{params.error && <p className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{decodeURIComponent(params.error)}</p>}<form action={saveServiceCategoryAction} className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-[1fr_1fr_120px_auto]"><input className={input} name="name" required placeholder="Nova categoria ou subcategoria" /><select className={input} name="parentId"><option value="">Categoria principal</option>{roots.map((root) => <option key={root.id} value={root.id}>Subcategoria de {root.name}</option>)}</select><input className={input} name="displayOrder" type="number" defaultValue={0} aria-label="Ordem" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked />Ativa</label><button className="rounded-xl bg-[#F2811D] px-5 py-3 font-bold text-white sm:col-span-4">Adicionar</button></form><div className="grid gap-3">{data?.map((category) => <form key={category.id} action={saveServiceCategoryAction} className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_1fr_100px_auto_auto]"><input type="hidden" name="id" value={category.id} /><input className={input} name="name" defaultValue={category.name} required /><select className={input} name="parentId" defaultValue={category.parent_id ?? ""} disabled={!category.parent_id}><option value="">Principal</option>{roots.filter((root) => root.id !== category.id).map((root) => <option key={root.id} value={root.id}>{root.name}</option>)}</select><input className={input} name="displayOrder" type="number" defaultValue={category.display_order} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={category.is_active} />Ativa</label><button className="rounded-xl bg-[#0F2D4E] px-4 py-2 text-xs font-bold text-white">Salvar</button><button formAction={deleteServiceCategoryAction} name="id" value={category.id} className="rounded-xl border border-red-200 px-4 py-2 text-xs font-bold text-red-700 md:col-start-5">Excluir</button></form>)}</div></AppShell>;
}
