import { Check, CircleDollarSign, Crown, Database, ShieldCheck, Sparkles } from "lucide-react";
import { AppShell } from "@/components/app/shell";
import { CompanyPlanSelector } from "@/components/company/company-plan-selector";
import { COMPANY_PLANS, getCompanyPlan, isCompanyPlanCode } from "@/lib/company-plans";
import { createServerClient } from "@/lib/supabase/server";

function Alert({ tone, children }: { tone: "error" | "success"; children: React.ReactNode }) { return <p className={`rounded-xl border px-4 py-3 text-sm font-medium ${tone === "error" ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{children}</p>; }

export default async function CompanyPlansPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const [params, supabase] = await Promise.all([searchParams, createServerClient()]);
  const { data: userData } = await supabase.auth.getUser();
  const { data: company } = await supabase.from("companies").select("trade_name,plan_code").eq("owner_id", userData.user?.id).maybeSingle();
  const storedPlanCode = company?.plan_code ?? "";
  const currentPlan = isCompanyPlanCode(storedPlanCode) ? storedPlanCode : "essential";
  const activePlan = getCompanyPlan(currentPlan);
  return <AppShell eyebrow="Empresa" title="Planos e condições"><div className="space-y-6 pb-8">
    {params.error ? <Alert tone="error">{params.error}</Alert> : null}
    {params.message === "plano-atualizado" ? <Alert tone="success">Plano atualizado com sucesso. As novas condições já estão registradas para sua empresa.</Alert> : null}
    <section className="relative overflow-hidden rounded-[1.75rem] bg-[#0F2D4E] px-5 py-7 text-white shadow-[0_20px_50px_rgba(15,45,78,0.2)] sm:px-8 sm:py-9"><div className="pointer-events-none absolute -right-16 -top-20 size-64 rounded-full border-[28px] border-[#F2811D]/20" /><div className="pointer-events-none absolute -bottom-24 left-1/2 h-40 w-80 -translate-x-1/2 rounded-[100%] border border-[#F2811D]/30" /><div className="relative grid gap-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div className="max-w-2xl"><p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#FFB36D]"><Sparkles aria-hidden="true" size={15} />Planos empresariais</p><h2 className="mt-3 font-display text-3xl font-bold tracking-tight sm:text-4xl">Contrate no ritmo da sua empresa.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-200 sm:text-base">Escolha a condição que combina com seu momento e acompanhe cada contratação pelo Portal Encaixe.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 backdrop-blur-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-300">Plano atual de {company?.trade_name ?? "sua empresa"}</p><p className="mt-1 flex items-center gap-2 font-display text-xl font-bold"><Crown aria-hidden="true" className="text-[#F2811D]" size={19} />{activePlan.name}</p></div></div></section>
    <section aria-label="Planos disponíveis" className="grid gap-5 lg:grid-cols-3 lg:items-stretch">{COMPANY_PLANS.map((plan) => { const isCurrent = plan.code === currentPlan; return <article key={plan.code} className={["relative flex min-w-0 flex-col overflow-hidden rounded-[1.5rem] border bg-white p-5 shadow-[0_12px_28px_rgba(15,45,78,0.08)] transition duration-200 motion-reduce:transition-none sm:p-6", plan.featured ? "border-[#F2811D] ring-1 ring-[#F2811D]/35 lg:-translate-y-2" : "border-slate-200 hover:-translate-y-1 hover:shadow-[0_18px_35px_rgba(15,45,78,0.13)]"].join(" ")}>
      {plan.featured ? <div className="-mx-5 -mt-5 mb-5 bg-[#F2811D] px-5 py-2 text-center text-xs font-extrabold uppercase tracking-[0.15em] text-white sm:-mx-6 sm:-mt-6 sm:px-6">Melhor custo-benefício</div> : null}
      <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#F2811D]">{plan.eyebrow}</p><h3 className="mt-2 font-display text-2xl font-bold text-[#0F2D4E]">{plan.name}</h3></div>{isCurrent ? <span className="rounded-full bg-[#0F2D4E] px-3 py-1 text-xs font-bold text-white">Atual</span> : null}</div><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">{plan.description}</p>
      <div className="mt-6 border-y border-slate-100 py-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Mensalidade fixa</p><p className="mt-1 font-display text-4xl font-bold tracking-tight text-[#0F2D4E]">{plan.monthlyPrice}<span className="ml-1 text-base font-semibold text-slate-500">/mês</span></p><div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><CircleDollarSign aria-hidden="true" className="text-[#F2811D]" size={18} /><span>Taxa por contratação: <strong className="text-[#0F2D4E]">{plan.hiringFee}</strong></span></div></div>
      <ul className="mt-5 space-y-3 text-sm leading-5 text-slate-700">{plan.benefits.map((benefit) => <li key={benefit} className="flex gap-2.5"><Check aria-hidden="true" className="mt-0.5 shrink-0 text-[#F2811D]" size={17} /><span>{benefit}</span></li>)}</ul><CompanyPlanSelector plan={plan} currentPlan={currentPlan} />
    </article>; })}</section>
    <section className="overflow-hidden rounded-[1.5rem] bg-[#0F2D4E] p-5 text-white shadow-[0_16px_34px_rgba(15,45,78,0.18)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FFB36D]">Comparação rápida</p><h2 className="mt-2 font-display text-2xl font-bold">Condições transparentes para cada fase.</h2></div><ShieldCheck aria-hidden="true" className="text-[#F2811D]" size={30} /></div><div className="mt-6 overflow-x-auto"><table className="min-w-[640px] w-full border-collapse text-left"><thead className="text-sm text-slate-300"><tr><th className="border-b border-white/15 px-3 py-3 font-semibold">Plano</th><th className="border-b border-white/15 px-3 py-3 font-semibold">Mensalidade fixa</th><th className="border-b border-white/15 px-3 py-3 font-semibold">Taxa por contratação efetivada</th><th className="border-b border-white/15 px-3 py-3 font-semibold">Principal benefício</th></tr></thead><tbody className="text-sm">{COMPANY_PLANS.map((plan) => <tr key={plan.code} className="border-b border-white/10 last:border-0"><td className="px-3 py-4 font-bold">{plan.name}</td><td className="px-3 py-4">{plan.monthlyPrice}/mês</td><td className="px-3 py-4">{plan.hiringFee}</td><td className="px-3 py-4 text-slate-200">{plan.benefits[0]}</td></tr>)}</tbody></table></div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-slate-300"><Database aria-hidden="true" className="mt-0.5 shrink-0 text-[#F2811D]" size={15} />A escolha do plano é registrada imediatamente para a empresa. A cobrança online será conectada ao módulo financeiro quando ele for definido.</p></section>
  </div></AppShell>;
}
