export const COURSE_PASSING_SCORE = 70;
export const COURSE_CERTIFICATION_BONUS_PER_MATCH = 20;
export const COURSE_CERTIFICATION_BONUS_CAP = 30;
export const COURSE_MAX_ATTEMPTS = 2;
export const COURSE_VIDEO_COMPLETION_PERCENT = 90;
