import { CheckCircle2, Clock3, ShieldAlert, XCircle } from "lucide-react";
import { AppShell } from "@/components/app/shell";
import { moderatePortfolioAction, moderateProviderAction } from "@/lib/actions/marketplace";
import { createServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const input = "rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#F2811D]";
export default async function AdminServiceProvidersPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; error?: string }> }) {
  const params = await searchParams;
  const supabase = await createServerClient();
  let query = supabase.from("service_provider_profiles").select("*,professionals(full_name,email,user_id)").order("submitted_at", { ascending: false });
  if (params.status) query = query.eq("status", params.status);
  const { data } = await query;
  const filtered = data?.filter((item) => !params.q || `${(item.professionals as { full_name?: string; email?: string })?.full_name} ${(item.professionals as { full_name?: string; email?: string })?.email} ${item.professional_title}`.toLowerCase().includes(params.q.toLowerCase()));
  const providerIds = filtered?.map((item) => item.id) ?? [];
  const { data: portfolio } = providerIds.length ? await supabase.from("service_provider_portfolio").select("id,provider_id,title,moderation_status").in("provider_id", providerIds).eq("moderation_status", "pending") : { data: [] };
  return <AppShell eyebrow="Administrador" title="Aprovação de prestadores">
    {params.error && <p className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{decodeURIComponent(params.error)}</p>}
    <form className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_220px_auto]"><input className={input} name="q" defaultValue={params.q} placeholder="Nome, e-mail ou serviço" /><select className={input} name="status" defaultValue={params.status ?? ""}><option value="">Todos os status</option><option value="pending">Pendentes</option><option value="approved">Aprovados</option><option value="rejected">Reprovados</option><option value="suspended">Suspensos</option></select><button className="rounded-xl bg-[#0F2D4E] px-5 py-2.5 font-bold text-white">Filtrar</button></form>
    <div className="grid gap-4">{filtered?.length ? filtered.map((provider) => { const professional = provider.professionals as { full_name?: string; email?: string }; const pendingImages = portfolio?.filter((item) => item.provider_id === provider.id) ?? []; return <article key={provider.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-xs font-bold uppercase text-[#F2811D]">{provider.status}</span><h2 className="text-xl font-bold text-[#0F2D4E]">{professional?.full_name}</h2><p className="text-sm text-slate-500">{professional?.email} · {provider.professional_title}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">Nota {Number(provider.rating_average).toFixed(1)}</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{provider.service_description}</p><p className="mt-3 text-xs text-slate-500">Especialidades: {provider.specialties?.join(", ") || "Não informadas"}</p><form action={moderateProviderAction} className="mt-4 grid gap-2 sm:grid-cols-[1fr_repeat(3,auto)]"><input type="hidden" name="providerId" value={provider.id} /><input className={input} name="reason" placeholder="Motivo obrigatório para reprovar/suspender" /><button name="status" value="approved" className="inline-flex items-center justify-center gap-1 rounded-xl bg-emerald-700 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 size={15} />Aprovar</button><button name="status" value="rejected" className="inline-flex items-center justify-center gap-1 rounded-xl bg-red-700 px-3 py-2 text-xs font-bold text-white"><XCircle size={15} />Reprovar</button><button name="status" value={provider.status === "suspended" ? "approved" : "suspended"} className="inline-flex items-center justify-center gap-1 rounded-xl bg-[#0F2D4E] px-3 py-2 text-xs font-bold text-white">{provider.status === "suspended" ? <Clock3 size={15} /> : <ShieldAlert size={15} />}{provider.status === "suspended" ? "Reativar" : "Suspender"}</button></form>{pendingImages.length > 0 && <div className="mt-4 rounded-xl bg-amber-50 p-4"><p className="text-xs font-bold text-amber-800">Portfólio aguardando moderação</p>{pendingImages.map((item) => <form key={item.id} action={moderatePortfolioAction} className="mt-2 flex items-center justify-between gap-2 text-sm"><input type="hidden" name="portfolioId" value={item.id} /><span>{item.title}</span><span className="flex gap-2"><button name="status" value="approved" className="rounded-lg bg-emerald-700 px-3 py-1.5 text-xs font-bold text-white">Aprovar</button><button name="status" value="removed" className="rounded-lg bg-red-700 px-3 py-1.5 text-xs font-bold text-white">Remover</button></span></form>)}</div>}</article>; }) : <p className="rounded-2xl bg-white p-8 text-center text-slate-500">Nenhum prestador encontrado.</p>}</div>
  </AppShell>;
}
