import Link from "next/link";
import { AlertCircle, CheckCircle2, Clock3, ImagePlus, MessageSquare, ShieldAlert, Store } from "lucide-react";
import { AppShell } from "@/components/app/shell";
import { ServicePostManager } from "@/components/marketplace/service-post-manager";
import { saveProviderProfileAction, uploadPortfolioAction } from "@/lib/actions/marketplace";
import { createServicePostSignedUrlMap, type ServicePost } from "@/lib/marketplace/explore";
import { createServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { isMarketplaceEnabled } from "@/lib/features";

export const dynamic = "force-dynamic";
const input = "mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#F2811D] focus:ring-4 focus:ring-orange-100";
const statusInfo: Record<string, { label: string; className: string; icon: typeof Clock3 }> = {
  pending: { label: "Em análise", className: "border-amber-200 bg-amber-50 text-amber-800", icon: Clock3 }, approved: { label: "Aprovado e visível", className: "border-emerald-200 bg-emerald-50 text-emerald-800", icon: CheckCircle2 }, rejected: { label: "Reprovado — corrija e reenvie", className: "border-red-200 bg-red-50 text-red-800", icon: AlertCircle }, suspended: { label: "Suspenso", className: "border-red-200 bg-red-50 text-red-800", icon: ShieldAlert }, banned: { label: "Função de prestador encerrada", className: "border-red-300 bg-red-50 text-red-900", icon: ShieldAlert }
};

export default async function ProfessionalServicesPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const params = await searchParams;
  const supabase = await createServerClient();
  if (!await isMarketplaceEnabled()) redirect("/professional/profile");
  const { data: userData } = await supabase.auth.getUser();
  const { data: professional } = await supabase.from("professionals").select("id,city,state").eq("user_id", userData.user?.id).maybeSingle();
  const [{ data: capability }, { data: provider }] = professional ? await Promise.all([
    supabase.from("professional_capabilities").select("provides_services").eq("professional_id", professional.id).maybeSingle(),
    supabase.from("service_provider_profiles").select("*").eq("professional_id", professional.id).maybeSingle()
  ]) : [{ data: null }, { data: null }];
  if (provider?.status === "banned") return <AppShell eyebrow="Profissional" title="Meus serviços"><section className="mx-auto max-w-2xl rounded-2xl border border-red-200 bg-white p-8 text-center shadow-sm"><ShieldAlert className="mx-auto text-red-700" size={40} /><p className="mt-4 text-xs font-bold uppercase tracking-wide text-red-700">Função de prestador encerrada</p><h2 className="mt-2 text-2xl font-bold text-[#0F2D4E]">O acesso à gestão de serviços foi encerrado definitivamente</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-600">Seu perfil não aparece mais nas buscas e não pode ser reativado. Esta medida afeta somente a oferta de serviços: seu currículo, candidaturas, vagas e cursos permanecem disponíveis normalmente.</p><Link href="/professional" className="mt-6 inline-flex rounded-xl bg-[#0F2D4E] px-5 py-3 text-sm font-bold text-white">Voltar para Explorar</Link></section></AppShell>;
  if (!capability?.provides_services) return <AppShell eyebrow="Profissional" title="Meus serviços"><section className="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><Store className="mx-auto text-[#F2811D]" size={36} /><h2 className="mt-4 text-xl font-bold text-[#0F2D4E]">Ative “Oferecer serviços” no seu perfil</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">Esta área é exclusiva para gerenciar o serviço que você oferece, portfólio, conversas recebidas e avaliações.</p><Link href="/professional/profile?offerServices=1" className="mt-5 inline-flex rounded-xl bg-[#0F2D4E] px-5 py-3 text-sm font-bold text-white">Ir para o Perfil</Link></section></AppShell>;
  const [{ data: categories }, { data: linked }, { data: areas }, { data: portfolio }, { data: posts }, { data: conversations }, { data: requests }, { data: reviews }] = await Promise.all([
    supabase.from("service_categories").select("id,name,parent_id").eq("is_active", true).order("display_order").order("name"),
    provider ? supabase.from("service_provider_categories").select("category_id").eq("provider_id", provider.id) : Promise.resolve({ data: [] }),
    provider ? supabase.from("service_provider_areas").select("*").eq("provider_id", provider.id).limit(1) : Promise.resolve({ data: [] }),
    provider ? supabase.from("service_provider_portfolio").select("*").eq("provider_id", provider.id).order("display_order") : Promise.resolve({ data: [] }),
    provider ? supabase.from("service_posts").select("id,images,description,created_at").eq("provider_id", provider.id).eq("status", "published").order("created_at", { ascending: false }) : Promise.resolve({ data: [] }),
    provider ? supabase.from("marketplace_conversations").select("id,status,last_message_at,created_at").eq("provider_id", provider.id).order("updated_at", { ascending: false }) : Promise.resolve({ data: [] }),
    provider ? supabase.from("service_requests").select("id,conversation_id,title,status,proposed_amount,created_at").eq("provider_id", provider.id).order("created_at", { ascending: false }) : Promise.resolve({ data: [] }),
    provider ? supabase.from("service_reviews").select("id,rating,comment,created_at").eq("provider_id", provider.id).eq("moderation_status", "approved").order("created_at", { ascending: false }).limit(10) : Promise.resolve({ data: [] })
  ]);
  const selected = new Set(linked?.map((item) => item.category_id));
  const area = areas?.[0];
  const info = provider ? statusInfo[provider.status] : null;
  const postRows = (posts ?? []) as ServicePost[];
  const postImageUrls = await createServicePostSignedUrlMap(supabase, postRows.flatMap((post) => post.images));
  const postsWithSignedUrls = postRows.map((post) => ({
    ...post,
    images: post.images.map((path) => postImageUrls.get(path)).filter((url): url is string => Boolean(url))
  })).filter((post) => post.images.length > 0);
  return <AppShell eyebrow="Profissional" title="Meu espaço de serviços">
    <div className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#0F2D4E] p-5 text-white md:col-span-2"><p className="text-xs font-bold uppercase tracking-wide text-orange-300">Emprego e serviços, na mesma conta</p><h2 className="mt-2 text-2xl font-bold">Ative seu perfil de prestador</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">Seus dados pessoais continuam únicos. Apenas as informações comerciais passam por aprovação antes de aparecerem nas buscas.</p></div><div className={`rounded-2xl border p-5 ${info?.className ?? "border-slate-200 bg-white text-slate-700"}`}>{info ? <><info.icon size={22} /><p className="mt-2 text-sm font-bold">{info.label}</p>{(provider.rejection_reason || provider.suspension_reason) && <p className="mt-2 text-xs leading-5">{provider.rejection_reason || provider.suspension_reason}</p>}</> : <><Store size={22} /><p className="mt-2 text-sm font-bold">Ainda não solicitado</p></>}</div></div>
    {(params.error || params.success) && <p className={`mb-5 rounded-xl border p-3 text-sm ${params.error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{params.error ? decodeURIComponent(params.error) : "Perfil enviado para análise."}</p>}
    {provider && userData.user ? <div className="mb-7"><ServicePostManager providerId={provider.id} userId={userData.user.id} initialPosts={postsWithSignedUrls} /></div> : null}
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
      <form action={saveProviderProfileAction} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div><h2 className="text-xl font-bold text-[#0F2D4E]">Perfil comercial</h2><p className="mt-1 text-sm text-slate-500">Uma nova edição volta para análise, exceto quando o perfil está suspenso.</p></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Título profissional<input className={input} name="professionalTitle" defaultValue={provider?.professional_title ?? ""} required minLength={3} placeholder="Ex.: Eletricista residencial" /></label><label className="text-sm font-semibold">Especialidades<input className={input} name="specialties" defaultValue={provider?.specialties?.join(", ") ?? ""} placeholder="Instalações, manutenção, reparos" /></label><label className="text-sm font-semibold sm:col-span-2">Descrição dos serviços<textarea className={input} name="serviceDescription" defaultValue={provider?.service_description ?? ""} required minLength={20} rows={5} /></label><label className="text-sm font-semibold">Modalidade<select className={input} name="serviceMode" defaultValue={provider?.service_mode ?? "in_person"}><option value="in_person">Presencial</option><option value="remote">Remoto</option><option value="both">Presencial e remoto</option></select></label><label className="text-sm font-semibold">Modelo de preço<select className={input} name="pricingModel" defaultValue={provider?.pricing_model ?? "negotiable"}><option value="fixed">Valor fixo</option><option value="hourly">Por hora</option><option value="quote">Orçamento</option><option value="negotiable">A combinar</option></select></label><label className="text-sm font-semibold">Valor inicial opcional<input className={input} name="startingPrice" type="number" min="0" step="0.01" defaultValue={provider?.starting_price ?? ""} /></label><label className="text-sm font-semibold">Disponibilidade<input className={input} name="availability" defaultValue={provider?.availability ?? ""} placeholder="Segunda a sábado" /></label><label className="text-sm font-semibold sm:col-span-2">Experiência e informações complementares<textarea className={input} name="experienceDescription" defaultValue={provider?.experience_description ?? ""} rows={4} /></label></div>
        <fieldset><legend className="text-sm font-bold text-[#0F2D4E]">Categorias e subcategorias</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{categories?.map((category) => <label key={category.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" name="categoryIds" value={category.id} defaultChecked={selected.has(category.id)} />{category.name}</label>)}</div></fieldset>
        <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-2 text-sm font-bold text-[#0F2D4E]">Área atendida</legend><label className="text-sm font-semibold">Cidade<input className={input} name="city" defaultValue={area?.city ?? professional?.city ?? ""} required /></label><label className="text-sm font-semibold">UF<input className={input} name="state" maxLength={2} defaultValue={area?.state ?? professional?.state ?? ""} required /></label><label className="text-sm font-semibold">Região ou bairros<input className={input} name="regionName" defaultValue={area?.region_name ?? ""} /></label><label className="text-sm font-semibold">Raio de atendimento (km)<input className={input} type="number" min={1} max={500} name="radiusKm" defaultValue={area?.radius_km ?? 20} /></label></fieldset>
        <button className="w-full rounded-xl bg-[#F2811D] px-5 py-3.5 font-bold text-white hover:bg-[#dd7010]">Salvar e enviar para análise</button>
      </form>
      <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-bold text-[#0F2D4E]"><MessageSquare size={19} />Operação</h2><div className="mt-4 grid gap-3"><div className="rounded-xl bg-slate-50 p-4"><strong className="text-2xl text-[#0F2D4E]">{conversations?.length ?? 0}</strong><p className="text-xs text-slate-500">conversas</p></div><div className="rounded-xl bg-slate-50 p-4"><strong className="text-2xl text-[#0F2D4E]">{requests?.length ?? 0}</strong><p className="text-xs text-slate-500">solicitações</p></div></div>{conversations?.slice(0,5).map((item) => <Link key={item.id} href={`/marketplace/conversations/${item.id}`} className="mt-3 block rounded-xl border border-slate-200 p-3 text-sm font-semibold text-[#0F2D4E] hover:border-orange-300">Abrir conversa · {new Date(item.last_message_at ?? item.created_at).toLocaleDateString("pt-BR")}</Link>)}</section>
        {provider && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-bold text-[#0F2D4E]"><ImagePlus size={19} />Portfólio</h2><form action={uploadPortfolioAction} className="mt-4 space-y-3"><input type="hidden" name="providerId" value={provider.id} /><input name="title" required className={input} placeholder="Título do trabalho" /><textarea name="description" className={input} placeholder="Descrição" /><input name="image" type="file" accept="image/png,image/jpeg,image/webp" required className="block w-full text-xs" /><button className="w-full rounded-xl bg-[#0F2D4E] px-4 py-3 text-sm font-bold text-white">Enviar imagem</button></form><div className="mt-4 space-y-2">{portfolio?.map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{item.title}</strong><span className="ml-2 text-xs text-slate-500">{item.moderation_status === "approved" ? "Aprovado" : "Em moderação"}</span></div>)}</div></section>}
        {provider && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-[#0F2D4E]">Avaliações recebidas</h2><div className="mt-3 space-y-3">{reviews?.length ? reviews.map((review) => <article key={review.id} className="rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold text-amber-600">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</p><p className="mt-1 text-slate-600">{review.comment || "Sem comentário."}</p></article>) : <p className="text-sm text-slate-500">Nenhuma avaliação recebida.</p>}</div></section>}
      </aside>
    </div>
  </AppShell>;
}
